version: '3.8'

services:
  app:
    build: .
    ports:
    - "8967:8967"
    container_name: excel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - laravel_network

  postgres:
    image: postgres:14
    container_name: excel_pgsql
    restart: unless-stopped
    environment:
      POSTGRES_DB: roows
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel_network

  web:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    depends_on:
      - app
    networks:
      - laravel_network
    
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - laravel_network

networks:
  laravel_network:

volumes:
  pgdata: